<?php

namespace ContainerW4TOiVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yj_9yywService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yj.9yyw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yj.9yyw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'webCrawler' => ['privates', 'App\\Service\\Crawler\\WebCrawler', 'getWebCrawlerService', true],
        ], [
            'webCrawler' => 'App\\Service\\Crawler\\WebCrawler',
        ]);
    }
}
