<?php

namespace ContainerW4TOiVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Document\DocumentController' shared autowired service.
     *
     * @return \App\Controller\Document\DocumentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Document/DocumentController.php';

        $container->services['App\\Controller\\Document\\DocumentController'] = $instance = new \App\Controller\Document\DocumentController();

        $instance->setContainer(($container->privates['.service_locator.PdRhP5Q'] ?? $container->load('get_ServiceLocator_PdRhP5QService'))->withContext('App\\Controller\\Document\\DocumentController', $container));

        return $instance;
    }
}
