<?php

namespace ContainerW4TOiVs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebCrawlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Crawler\WebCrawler' shared autowired service.
     *
     * @return \App\Service\Crawler\WebCrawler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Crawler/WebCrawler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/filesystem/Filesystem.php';

        return $container->privates['App\\Service\\Crawler\\WebCrawler'] = new \App\Service\Crawler\WebCrawler(($container->privates['filesystem'] ?? ($container->privates['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
    }
}
